Fix test artifact upload path incorrectly
cloudberrydb/cloudberrydb pull request #118
Opened 2023-08-04 03:19 UTC by sandiandian

closes: #ISSUE_Number

---

### Change logs

_Describe your change clearly, including what problem is being solved or what feature is being added._

_If it has some breaking backward or forward compatibility, please clary._

### Why are the changes needed?

_Describe why the changes are necessary._

### Does this PR introduce any user-facing change?

_If yes, please clarify the previous behavior and the change this PR proposes._

### How was this patch tested?

_Please detail how the changes were tested, including manual tests and any relevant unit or integration tests._

### Contributor's Checklist

Here are some reminders and checklists before/when submitting your pull request, please check them:

- [ ] Make sure your Pull Request has a clear title and commit message. You can take [git-commit](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) template as a reference.
- [ ] Sign the Contributor License Agreement as prompted for your first-time contribution.
- [ ] List your communication in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
- [ ] Document changes.
- [ ] Add tests for the change
- [ ] Pass `make installcheck`
- [ ] Pass `make -C src/test installcheck-cbdb-parallel`
- [ ] Feel free to @cloudberrydb/dev team for review and approval when your PR is ready🥳

2023-08-04 03:29 UTC, sandiandian commented
You need to wait for the test result to fail to verify that the path is correct, so please don't merge for now.

2023-08-14 02:05 UTC, tuhaihe commented
Hi @baotingfang @my-ship-it, Plz help review this PR, thanks!

2023-08-14 07:52 UTC, sandiandian commented
Failed test files can now be uploaded correctly

2023-08-14 07:53 UTC, sandiandian commented
@baotingfang @my-ship-it Failed test files can now be uploaded correctly

2023-08-22 05:30 UTC, my-ship-it commented
Please add detailed commit messages.

2023-09-06 01:25 UTC, my-ship-it commented
@sandiandian Please add more detailed commit message? In addition, have we tested it?

2023-10-11 07:02 UTC, Ray-Eldath commented
I use this PR's path in #206. we have many intermittent failure (e.g., https://github.com/cloudberrydb/cloudberrydb/actions/runs/6477388919) that do not have log files which make them super hard to diagnose. we need to merge this asap.

2023-10-11 08:45 UTC, tuhaihe requested changes
@sandiandian Thanks for updating your commit message. Please rewrite them again to fix the typos and add the missing period.

2023-10-12 02:18 UTC, tuhaihe commented
The format of the latest commit message appears good to me. Thank you! cc @sandiandian @Ray-Eldath

2023-10-12 02:22 UTC, tuhaihe approved these changes

2023-10-17 02:34 UTC, my-ship-it approved these changes
LGTM

2023-10-17 05:37 UTC, tuhaihe commented
@Zhangbaowen-Hashdata could you help update the commit message?

2023-10-19 01:50 UTC, closed without merging

2023-10-19 01:50 UTC, tuhaihe commented
Since the new PR #240 has been merged, close it #118 now. If something wrong, please reopen it, thanks!